### ISSUE TITLE
TODO: 23-05-27

### ISSUE THREAD

**Issue by hyewoniiiii** [sosotable/ssossotable#28]
- [ ] 사진 한 장에 글자 수는 100글자로 제한 (공백 포함 x)
- [ ] 사진에 공감하는 거 -> 좋아요 말고 자신이 선택한 이모티콘으로 공감할 수 있게
- [ ] 아이콘 누르면 숫자 올라가는 거 -> 공감하는 걸로 (한 사람당 한 번씩만 누를 수 있게, 다시 누르면 취소)
- [ ] 메인 홈 화면을 다이어리로
- [ ] 남이 나한테 태그 추가하면 -> 나한테 알림이 뜸 -> 프로필에 표시할지 말지 선택할 수 있게
- [ ] 앱 이름을 소소식탁으로 계속 유지하는 게 맞나?
- [ ] 로고 바꿨으면 좋겠다
- [ ] 글씨체 귀여운 걸로 바꾸기
- [ ] 다이어리에 달, 요일 표현 영어/한글?

앞으로 정해야 할 것들
